### ISSUE TITLE
How can one tell if this is working?

### ISSUE THREAD

**Issue by awhitford** [FasterXML/jackson-module-afterburner#50]
I have projects that use [JBoss Resteasy](http://resteasy.jboss.org/) and the [ResteasyJackson2Provider](https://github.com/resteasy/Resteasy/blob/master/jaxrs/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java) which extends `JacksonJaxbJsonProvider`.

I would like to add Afterburner.  Adding the dependency is easy enough.  I noticed that the `jackson-module-afterburner` has a `META-INF/services/com.fasterxml.jackson.databind.Module` file that would seem to indicate that it automatically registers `com.fasterxml.jackson.module.afterburner.AfterburnerModule`...  If so, does that mean that the [Registering module](https://github.com/FasterXML/jackson-module-afterburner#registering-module) instructions are not necessary?

If it is not automatically registering, then I'm puzzled how to get a hold of the underlying `ObjectMapper` instance so that `registerModule(new AfterburnerModule())` may be called.

**Comment by cowtowncoder** [comment]
Metadata information is included to be potentially used by other systems. Jackson tries to avoid automatic magic actions, so it does not by default try auto-detect such registrations.

However, ObjectMapper does have `findAndRegisterModules()` as well as `findModules()` which do use this SPI mechanism for locating and/or registering modules.

As to how you can locate Resteasy instance, that is something Resteasy mailing lists can hopefully help. Jackson does not track instantiations and it is up to frameworks to expose instance(s) they use.
