### ISSUE TITLE
Invalidating SerializationInclusion.NON_NULL of other modules

### ISSUE THREAD

**Issue by natnan** [FasterXML/jackson-module-afterburner#52]
https://github.com/zapodot/jackson-databind-java-optional/issues/2

#### tl;dr

If a different module with custom SerializationInclusion handling is registered after AfterBurnerModule, nulls are de/serialized still as nulls, ignoring the other module. The workaround is to
- Register the other module first. Not possible when one uses dropwizard for example.
- Add @JsonProperty to those specific fields. Not pretty when one has many of those.

Unit tests are available in the issue above.

**Comment by cowtowncoder** [comment]
Unit test much appreciated. Usually problems like this are due to optimized handling which may not take into account all processing logic that is being added. The reason why pre-registration may work is if serializer is constructed first before afterburner has a chance to add optimized handler.

**Comment by cowtowncoder** [comment]
Hmmh. Actually, it might not be that easy to see what is going on, as this appear to involve additional serializers from linked-to project. It would be good to have a stand-alone unit test that exhibits the problem only using classes declared in test class itself, to isolate the problem.

**Comment by natnan** [comment]
The serializer is a bit silly but does the job :).

```java
public class SampleObject {
  private String field1;
  private Integer field2;
  private Integer field3;

  public SampleObject(String field1, Integer field2, Integer field3) {
    this.field1 = field1;
    this.field2 = field2;
    this.field3 = field3;
  }

// getter setters
}

public class NullSerializerTest {

  @Test
  public void test() throws JsonProcessingException {
    SampleObject sampleObject = new SampleObject(null, 2, 3);

    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(new AfterburnerModule());

    SimpleModule simpleModule = new SimpleModule();
    simpleModule.addSerializer(new Only2Serializer());
    objectMapper.registerModule(simpleModule);
    objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    String json = objectMapper.writeValueAsString(sampleObject);

    assertEquals("{\"field2\":\"2\"}", json);
  }

  public class Only2Serializer extends StdSerializer<Integer> {

    public Only2Serializer(){
      super(Integer.class);
    }

    @Override
    public void serialize(Integer value, JsonGenerator jgen, SerializerProvider provider) throws IOException {
      if(value.equals(2)) {
        provider.defaultSerializeValue("2", jgen);
      } else {
        provider.defaultSerializeNull(jgen);
      }
    }
  }
}
```

```
org.junit.ComparisonFailure: 
Expected :{"field2":"2"}
Actual   :{"field2":"2","field3":null}
```

**Comment by natnan** [comment]
Oh wait, it failed without AfterBurner as well. Hmm..

**Comment by natnan** [comment]
OK, fixed it. Probably can be simplified though.

It looks like it ignores the SerializerModifier when AfterBurner is registered.

**Comment by cowtowncoder** [comment]
Thanks -- that sounds plausible, yes. Need to see what checks need to be added to avoid optimizing this case.

**Comment by cowtowncoder** [comment]
Accidentally closed the wrong issue.

**Comment by cowtowncoder** [comment]
Ah. Just realized that a more likely explanation is the ordering of modules.

If so, not sure if this actually can be solved or not.

**Comment by cowtowncoder** [comment]
Turned out there is another way to solve this problem, by blocking use of optimized `BeanPropertyWriter` subtype of bpw given is a custom type.

**Comment by natnan** [comment]
:+1:, thanks.
