### ISSUE TITLE
Afterburner does not respect DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS

### ISSUE THREAD

**Issue by shollander** [FasterXML/jackson-module-afterburner#56]
Afterburner does not respect ```DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS```.
I get this error:

>Can not deserialize instance of java.lang.String out of START_ARRAY token

**Comment by cowtowncoder** [comment]
Looks like handling was indeed incomplete. I hope fix is complete, without specific unit tests hard to be sure. But I did add couple of tests that failed before fix, now pass.
