### ISSUE TITLE
Illegal class name "Lcom/fasterxml/jackson/module/afterburner/deser/OptimizedValueInstantiator;"

### ISSUE THREAD

**Issue by kierannichol** [FasterXML/jackson-module-afterburner#68]
Running on openjdk 1.8.0_111

Getting the following exception while deserializing class:

Caused by: java.lang.ClassFormatError: Illegal class name "Lcom/fasterxml/jackson/module/afterburner/deser/OptimizedValueInstantiator;" in class file com/example/ExampleClass$Creator4JacksonDeserializer433a52e6
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.fasterxml.jackson.module.afterburner.util.MyClassLoader.loadAndResolve(MyClassLoader.java:94)
	... 114 common frames omitted

**Comment by cowtowncoder** [comment]
Which version of Jackson, afterburner?

**Comment by kierannichol** [comment]
Sorry, that would probably help. We saw this on 2.9.0.pr3, but not seeing it on 2.9.0.pr1.

**Comment by cowtowncoder** [comment]
Hmmh. That is interesting... would have hoped it went the other way.

The odd thing is that all unit test for Afterburner pass for Java 8 versions I use (current 1.8.0_152, but I have used various older versions). This is with the oracle's standard Jdk on MacOS.

So basically I do not have a way to reproduce the problem at this point.

**Comment by olamy** [comment]
Same issue here.
Maybe you should run the tests on a docker image :-)

**Comment by cowtowncoder** [comment]
@olamy at this point it's question of having a reproduction: not that there'd be one that sometimes works. So... I really would need to know how to reproduce this. Stand-alone project that fails somewhere would be great.

**Comment by olamy** [comment]
ok I understand. I will try to get something out of the close source project I'm working on.

**Comment by stevestorey** [comment]
Hello. I too encountered the same issue, and have been able to create a reproduction - though not sadly in the form of a unit test.

If you build the WAR from https://github.com/stevestorey/afterburner-class-load-repro via `mvn package`, and then deploy the WAR to a Wildfly 10.1.0.Final instance, and then run:
`curl -XPOST -HContent-type:application/json --data {} http://localhost:8080/test-afterburner-bug-0.0.1-SNAPSHOT/echo` you should encounter the exception above.

Worth noting that you don't get the exception if you just run the Spring Boot WAR with Tomcat or Undertow, so it looks like at least in my case, it's something specific to do with an interaction between Afterburner and the Wildfly classloaders. I've not been able to isolate what yet, nor create a workaround, hence posting what I do have here.

**Comment by stevestorey** [comment]
Bit more info - using 2.9.0.pr4 for everything except afterburner, and doing a git bisect suggests that commit https://github.com/FasterXML/jackson-modules-base/commit/7450e0a65cef41691762b0695edc0a0b40d22735 is the culprit

**Comment by stevestorey** [comment]
I worked out what the problem was - was the first parameter to INVOKEVIRTUAL being apparently indeed in the wrong format (apparently needs to be `com/fasterxml/x/y/SomeClass` rather than the type descriptor `Lcom/fasterxml/x/y/SomeClass;`. I've made https://github.com/FasterXML/jackson-modules-base/pull/27 for the fix
